[package]
name = "yang-base"
version = "0.1.0"
edition = "2021"

description = "个人使用构建后端服务器"
license = "MIT OR Apache-2.0"

#排除文件
exclude = [
    "INSTALL.md",
]

[dependencies]
# 内部依赖
yang-db = { version = "0.1.2" }

# 异步运行时
tokio = { version = "1.52.1", features = ["full"] }
async-trait = "0.1.89"

# 序列化
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.140"

# 错误处理
thiserror = "2.0.18"

# 日志
log = "0.4.29"

# HTTP 客户端
reqwest = { version = "0.13.2", features = ["json", "query"] }

# JWT Token
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }

# 工具库
uuid = { version = "1.23.1", features = ["v4"] }
chrono = "0.4.44"
regex = "1.12.3"

# 数据库
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "mysql"] }


[dev-dependencies]
tokio = { version = "1.52.1", features = ["full", "test-util"] }
testcontainers = "0.27.3"
env_logger = "0.11.10"

