[package]
name = "yang-base-derive"
version = "0.2.1"
edition.workspace = true
description = "yang-base 类型化 Action 派生宏"
license.workspace = true
authors.workspace = true
repository.workspace = true
documentation = "https://docs.rs/yang-base-derive"
readme = "README.md"
keywords = ["derive", "macro", "proc-macro", "yang-base"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
darling = { workspace = true }
