[package]
name = "yang-db"
version = "0.1.0"
edition = "2024"

description = "个人使用数据库操作"
license = "MIT OR Apache-2.0"

#排除文件
exclude = [
    "INSTALL.md",
]

[dependencies]
deadpool-redis = "0.23.0"
redis = "1.1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "mysql", "chrono", "json"] }
tokio = { version = "1.51.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
chrono = "0.4"
log = "0.4"
base64 = "0.22"

[dev-dependencies]
proptest = "1.5"
